Feature: To check the subscription catlog is displayed correctly for PLE601

  @catlogin @PLE601
  Scenario: Naviagation and searching the asset details
    When Navigate to "My worklist"
    Then The page "Myworklist" should be displayed
    When search Asset details as "UIT00127" in My Worklist Page

  @catlogin @PLE601
  Scenario Outline: To check whether subscriptions are populated properly in Customer,cat and Dealer subscription dropdown for the device Type PLE601 when logged in as CAT.
    #When search Asset details as "<S/N>" in My Worklist Page
    And select the services as "<Services>" from subscriptions page
    Then verify whether the subscription dropdown values "<Customer>","<Dealer>","<Cat>"  are populated according to the selected service

    Examples: 
      | Device Type | S/N      | Services                | Customer                                                                                                                                                                                                                                                                                                                                                  | Dealer                                                                                                                                                                                                                                                                                                                                                    | Cat                                                                                                                                                                                                                                                                                                                                                                                                            |
      | PLE601      | UIT00127 | PRODUCT LINK WEB        | Vitals (EE1-4 ) - Customer Supplied Connection,Aide (EE4-14 ) - Customer Supplied Connection,Aide (EE4-14-T ) - Customer Supplied Connection,Advisor (EE24-54 ) - Customer Supplied Connection,Advisor (EE24-54-T ) - Customer Supplied Connection ,Advisor (EE24-104 ) - Customer Supplied Connection,Advisor (EE24-204 ) - Customer Supplied Connection | Vitals (EE1-4 ) - Customer Supplied Connection,Aide (EE4-14 ) - Customer Supplied Connection,Aide (EE4-14-T ) - Customer Supplied Connection,Advisor (EE24-54 ) - Customer Supplied Connection,Advisor (EE24-54-T ) - Customer Supplied Connection ,Advisor (EE24-104 ) - Customer Supplied Connection,Advisor (EE24-204 ) - Customer Supplied Connection | Vitals (EE1-4 ) - Customer Supplied Connection,Aide (EE4-14 ) - Customer Supplied Connection,Aide (EE4-14-T ) - Customer Supplied Connection,Advisor (EE24-54 ) - Customer Supplied Connection,Advisor (EE24-54-T ) - Customer Supplied Connection ,Advisor (EE24-104 ) - Customer Supplied Connection,Advisor (EE24-204 ) - Customer Supplied Connection,Advisor streaming,ECA Batch Data Service (E C24 ECA) |
      | PLE601      | UIT00127 | MY.CAT.COM              | Cat Daily                                                                                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                |
      | PLE601      | UIT00127 | EQUIPMENT TRACKER       | Cat Daily                                                                                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                |
      #| PLE601      | UIT00127 | PRODUCT LINK GENERATION |                                                                                                                                                                                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                                                                           | Base,Comp,Custom                                                                                                                                                                                                                                                                                                                                                                                               |

  #Query:PLG is for cat level
  @catlogin @PLE601
  Scenario Outline: To chek whether the Add-Ons are displayed properly for PLE601 subscriptions
    #When search Asset details as "<S/N>" in My Worklist Page
    And select the services as "<Services>" from subscriptions page
    And select the subscriptions as "<Customer>","<Dealer>","<Cat>"
    Then verify whether the Add-On services are displayed as "<Additional Services>"

    Examples: 
      | Device Type | S/N      | Services         | Customer | Dealer | Cat                                                 | Additional Services |
      | PLE601      | UIT00127 | PRODUCT LINK WEB |          |        | Vitals (EE1-4 ) - Customer Supplied Connection      | Onboard Analytics   |
      | PLE601      | UIT00127 | PRODUCT LINK WEB |          |        | Aide (EE4-14 ) - Customer Supplied Connection       | Onboard Analytics   |
      | PLE601      | UIT00127 | PRODUCT LINK WEB |          |        | Aide (EE4-14-T ) - Customer Supplied Connection     | Onboard Analytics   |
      | PLE601      | UIT00127 | PRODUCT LINK WEB |          |        | Advisor (EE24-54 ) - Customer Supplied Connection   | Onboard Analytics   |
      | PLE601      | UIT00127 | PRODUCT LINK WEB |          |        | Advisor (EE24-54-T ) - Customer Supplied Connection | Onboard Analytics   |
      | PLE601      | UIT00127 | PRODUCT LINK WEB |          |        | Advisor (EE24-104 ) - Customer Supplied Connection  | Onboard Analytics   |
      | PLE601      | UIT00127 | PRODUCT LINK WEB |          |        | Advisor (EE24-204 ) - Customer Supplied Connection  | Onboard Analytics   |
      | PLE601      | UIT00127 | PRODUCT LINK WEB |          |        | ECA Batch Data Service (E C24 ECA)                  | Onboard Analytics   |

  @dealerlogin
  Scenario Outline: To check whether subscriptions are populated properly in Customer,cat and Dealer subscription dropdown for the device Type PLE601 when logged in as dealer.
    When search Asset details as "<S/N>" in My Worklist Page
    And select the services as "<Services>" from subscriptions page
    Then verify whether the subscription dropdown values "<Customer>","<Dealer>","<Cat>"  are populated according to the selected service

    Examples: 
      | Device Type | S/N      | Services                | Customer Level Subscription                                                                                                                                                                                                                                                                                                                               | Dealer | Cat              |
      | PLE601      | UIT00127 | PRODUCT LINK WEB        | Vitals (EE1-4 ) - Customer Supplied Connection,Aide (EE4-14 ) - Customer Supplied Connection,Aide (EE4-14-T ) - Customer Supplied Connection,Advisor (EE24-54 ) - Customer Supplied Connection,Advisor (EE24-54-T ) - Customer Supplied Connection ,Advisor (EE24-104 ) - Customer Supplied Connection,Advisor (EE24-204 ) - Customer Supplied Connection |        |                  |
      | PLE601      | UIT00127 | MY.CAT.COM              | Cat Daily                                                                                                                                                                                                                                                                                                                                                 |        |                  |
      | PLE601      | UIT00127 | EQUIPMENT TRACKER       | Cat Daily                                                                                                                                                                                                                                                                                                                                                 |        |                  |
      | PLE601      | UIT00127 | PRODUCT LINK GENERATION |                                                                                                                                                                                                                                                                                                                                                           |        | Base,Comp,Custom |

  #Query:PLG is for cat level
  @customerlogin
  Scenario Outline: To check whether subscriptions are populated properly in Customer,cat and Dealer subscription dropdown for the device Type PLE601 when logged in as Customer.
    When search Asset details as "<S/N>" in My Worklist Page
    And select the services as "<Services>" from subscriptions page
    Then verify whether the subscription dropdown values "<Customer>","<Dealer>","<Cat>"  are populated according to the selected service

    Examples: 
      | Device Type | S/N      | Services                | Customer Level Subscription                                                                                                                                                                                                                                                                                                                               | Dealer                                                                                                                                                                                                                                                                                                                                                    | Cat              |
      | PLE601      | UIT00127 | PRODUCT LINK WEB        | Vitals (EE1-4 ) - Customer Supplied Connection,Aide (EE4-14 ) - Customer Supplied Connection,Aide (EE4-14-T ) - Customer Supplied Connection,Advisor (EE24-54 ) - Customer Supplied Connection,Advisor (EE24-54-T ) - Customer Supplied Connection ,Advisor (EE24-104 ) - Customer Supplied Connection,Advisor (EE24-204 ) - Customer Supplied Connection | Vitals (EE1-4 ) - Customer Supplied Connection,Aide (EE4-14 ) - Customer Supplied Connection,Aide (EE4-14-T ) - Customer Supplied Connection,Advisor (EE24-54 ) - Customer Supplied Connection,Advisor (EE24-54-T ) - Customer Supplied Connection ,Advisor (EE24-104 ) - Customer Supplied Connection,Advisor (EE24-204 ) - Customer Supplied Connection |                  |
      | PLE601      | UIT00127 | MY.CAT.COM              | Cat Daily                                                                                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                                                                                                                                           |                  |
      | PLE601      | UIT00127 | EQUIPMENT TRACKER       | Cat Daily                                                                                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                                                                                                                                           |                  |
      | PLE601      | UIT00127 | PRODUCT LINK GENERATION |                                                                                                                                                                                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                                                                           | Base,Comp,Custom |
#Query:PLG is for cat level
